# Generated by Django 5.0 on 2023-12-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO_customer', models.CharField(max_length=255, verbose_name='ФИО покупателя')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('MG', 'Магазин'), ('CR', 'Курьер'), ('PP', 'Пункт выдачи')], default='MG', max_length=2, verbose_name='Способ доставки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('agent_firstname', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('agent_patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество представителя')),
                ('agent_telephone', models.CharField(max_length=255, verbose_name='Телефон представителя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тега')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Pos_parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение характеристики')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.parametr', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Позиция характеристики',
                'verbose_name_plural': 'Позиции характеристик',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='magazine/%Y/%m/%d', verbose_name='Фотография книги')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует ли?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.category')),
                ('parametr', models.ManyToManyField(through='magazine.Pos_parametr', to='magazine.parametr')),
                ('tag', models.ManyToManyField(blank=True, to='magazine.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Pos_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
        migrations.AddField(
            model_name='pos_parametr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество продукта')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка продукта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='magazine.Pos_order', to='magazine.product'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supply', models.DateTimeField(verbose_name='Дата поставки')),
                ('product', models.ManyToManyField(through='magazine.Pos_supply', to='magazine.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.AddField(
            model_name='pos_supply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazine.supply', verbose_name='Поставка'),
        ),
    ]
