# Generated by Django 5.0 on 2023-12-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['date_supply'], 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
    ]
