# Generated by Django 5.0 on 2024-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='magazine',
            field=models.ImageField(blank=True, upload_to='magazine/hehehe/', verbose_name='фотка'),
        ),
    ]
