# Generated by Django 5.0 on 2024-01-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_supplier_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='magazine',
        ),
    ]
